[d3d12]
adapter = 0
backBufferCount = 2
dsvHeapSize = 16
rtvHeapSize = 16
srvHeapSize = 1024

[depot]
maxFileHandles = 0
waitInterval = 100

    [depot.vfs]
    mode = 'read'
    root = '$exe'

[game]
entityLimit = 4096
seed = 0

[input]
keyboardenable = true
mousecapture = false
mouseenable = true
poll-interval = 16

    [input.xinput]
    gamepad0 = true

[logging]
level = 'info'

    [logging.console]
    colour = true

    [logging.file]
    path = 'engine.log'

[platform.window]
height = 720
title = 'simcoe'
width = 1280

[render]
faultLimit = 0

    [render.display]
    height = 1080
    width = 1920

[threads]
mainQueueSize = 64
workQueueSize = 256

    [threads.workers]
    delay = 50
    initial = 0
    max = 0