[d3d12.adapter]
default_index = 0
lookup_method = 'default'

[d3d12.debug]
debug_layer = false
dred = false
info_queue = false

[d3d12.heaps]
dsv_count = 16
rtv_count = 16
srv_count = 1024

[depot]
max_file_handles = 128
wait_interval = 100

    [depot.vfs]
    mode = 'read'
    root = '$exe'

[game]
entity_limit = 4096
seed = 0

    [game.render]
    adapter = 0
    backBufferCount = 2
    draw_height = 1080
    draw_width = 1920

[input]
keyboard_enable = true
poll_interval = 500

    [input.mouse]
    capture_input = false
    enable = true

    [input.xinput]
    gamepad0_enable = true

[logging]
level = 'info'

    [logging.console]
    colour = true

    [logging.file]
    path = 'engine.log'

[platform.window]
height = 720
title = 'simcoe'
width = 1280

[render]
fault_limit = 1

[threads]
mainQueueSize = 64
workQueueSize = 256

    [threads.workers]
    delay = 50
    initial = 0
    max = 0